### ISSUE TITLE
Javascript user actions/behavoir modeling

### ISSUE THREAD

**Issue by th31nitiate** [fogfish/typhoon#3]
Hello,

I'm just wondering if there is anyway in your view that you see this application being able to handle user interaction modeling via java script ?

I understand it does not use a browser and it is more geared towards working with API services. Though im just wondering given its architecture is they anyway you can envision it being able to model user actions and behavior via java script ?

**Comment by fogfish** [comment]
I do not think it is possible to make it. Please check https://github.com/grafana/k6 if you are interesting about pure JavaScript solution.

**Comment by th31nitiate** [comment]
> I do not think it is possible to make it. Please check https://github.com/grafana/k6 if you are interesting about pure JavaScript solution.

Yh, that was the original solution but I wondered when I seen this is beam based. Keeping every thing self consistent in the language would of been great. Though no worries I appreciate your response.

**Comment by fogfish** [comment]
If this make your life easier... There is a Golang toolkit https://github.com/fogfish/gurl for similar syntax on the load creation...

**Comment by th31nitiate** [comment]
> If this make your life easier... There is a Golang toolkit https://github.com/fogfish/gurl for similar syntax on the load creation...

Thanks this look cool too and the programmability would be useful though not to worry. It is just me being a little bougie,

![8gcmh6](https://github.com/fogfish/typhoon/assets/14749635/268861a1-3126-4821-b5fc-2cb583658473)

If I take the simple path the framework I use can easily create JSON API's. This will solve my problem by allowing me to submit user data directly to the event functions. The event functions are call back from the browser when a user enters data to the web page and click's submit, it triggers the event function.

Writing the user tests can be achieved by writing a module that represents aspects of user behavior. Ultimately this will allow me to see how data moves through the entire system. The only issue I foresee is the front-end will technically not be involved in this flow, but its server side rendering. This can ideally be measured by other means. 

I can measure the page load time (By gets) then instead of submitting data this way I submit it via the test specific API's via a post. I can load/rendering the page load time and then instead of submitting data this way I submit it via the test specific API's via post.

Thanks for your input as sometimes it take time for us to comprehend suitable solutions as this did not seem obvious to me from the onset, though after sometime introspecting on the issue this solutions came to mind, and now I'll create a card to test it in the upcoming weeks.
